config/routes.rb
Rails.application.routes.draw do
  root to: "rentals#index"
  resources :rentals
  resources :cars
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :user
  belongs_to :car

  after_create :send_confirmation
  
  private

  def send_confirmation
    RentalMailer.with(rental: self).confirmation.deliver_later!
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    logger.tagged "Add CAR" do
      logger.info "Creating object"
      @car = Car.new(car_params)
      logger.info "Saving a car"
      @saved = @car.save
    end

    respond_to do |format|
      if @saved
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:name, :manufacturer, :year, :additional_information)
    end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :set_rental, only: [:show, :edit, :update, :destroy]

  # GET /rentals
  # GET /rentals.json
  def index
    @rentals = Rental.all
  end

  # GET /rentals/1
  # GET /rentals/1.json
  def show
  end

  # GET /rentals/new
  def new
    @rental = Rental.new
  end

  # GET /rentals/1/edit
  def edit
  end

  # POST /rentals
  # POST /rentals.json
  def create
    @rental = Rental.new(rental_params)

    respond_to do |format|
      if @rental.save
        format.html { redirect_to @rental, notice: 'Rental was successfully created.' }
        format.json { render :show, status: :created, location: @rental }
      else
        Rollbar.error("Error when trying to rent a car")
        format.html { render :new }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rentals/1
  # PATCH/PUT /rentals/1.json
  def update
    respond_to do |format|
      if @rental.update(rental_params)
        format.html { redirect_to @rental, notice: 'Rental was successfully updated.' }
        format.json { render :show, status: :ok, location: @rental }
      else
        format.html { render :edit }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rentals/1
  # DELETE /rentals/1.json
  def destroy
    @rental.destroy
    respond_to do |format|
      format.html { redirect_to rentals_url, notice: 'Rental was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rental
      @rental = Rental.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rental_params
      params.require(:rental).permit(:start_date, :end_date, :user_id, :car_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/views/cars/_form.html.erb
<%= form_with(model: car, local: true) do |form| %>
  <% if car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :car_name %>
  </div>

  <div class="field">
    <%= form.label :manufacturer %>
    <%= form.text_field :manufacturer, id: :car_manufacturer %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year, id: :car_year %>
  </div>

  <div class="field">
    <%= form.label :additional_information %>
    <%= form.text_area :additional_information, id: :car_additional_information %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cars</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Manufacturer</th>
      <th>Year</th>
      <th>Additional information</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.name %></td>
        <td><%= car.manufacturer %></td>
        <td><%= car.year %></td>
        <td><%= car.additional_information %></td>
        <td><%= link_to 'Show', car %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car', new_car_path %>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @car.name %>
</p>

<p>
  <strong>Manufacturer:</strong>
  <%= @car.manufacturer %>
</p>

<p>
  <strong>Year:</strong>
  <%= @car.year %>
</p>

<p>
  <strong>Additional information:</strong>
  <%= @car.additional_information %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentCars</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= link_to "Cars", cars_path %>
      <%= link_to "Rentals", rentals_path %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/layouts/old_mailer_1515171387.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style>
      /* Email styles need to be inline */
    </style>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rentals/_form.html.erb
<%= form_with(model: rental, local: true) do |form| %>
  <% if rental.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rental.errors.count, "error") %> prohibited this rental from being saved:</h2>

      <ul>
      <% rental.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.datetime_select :start_date, id: :rental_start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.datetime_select :end_date, id: :rental_end_date %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.collection_select :user_id, User.all, :id, :email %>
  </div>

  <div class="field">
    <%= form.label :car_id %>
    <%= form.collection_select :car_id, Car.all, :id, :name, include_blank: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rentals/edit.html.erb
<h1>Editing Rental</h1>

<%= render 'form', rental: @rental %>

<%= link_to 'Show', @rental %> |
<%= link_to 'Back', rentals_path %>

app/views/rentals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rentals</h1>

<table>
  <thead>
    <tr>
      <th>Start date</th>
      <th>End date</th>
      <th>User</th>
      <th>Car</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rentals.each do |rental| %>
      <tr>
        <td><%= rental.start_date %></td>
        <td><%= rental.end_date %></td>
        <td><%= rental.user.email %></td>
        <td><%= rental.car.name %></td>
        <td><%= link_to 'Show', rental %></td>
        <td><%= link_to 'Edit', edit_rental_path(rental) %></td>
        <td><%= link_to 'Destroy', rental, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rental', new_rental_path %>

app/views/rentals/new.html.erb
<h1>New Rental</h1>

<%= render 'form', rental: @rental %>

<%= link_to 'Back', rentals_path %>

app/views/rentals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start date:</strong>
  <%= @rental.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @rental.end_date %>
</p>

<p>
  <strong>User:</strong>
  <%= @rental.user.email %>
</p>

<p>
  <strong>Car:</strong>
  <%= @rental.car.name %> - <%= @rental.car.manufacturer %>
</p>

<%= link_to 'Edit', edit_rental_path(@rental) %> |
<%= link_to 'Back', rentals_path %>